### PR TITLE
authNRequest fixes and other changes

### LINKED ISSUE #10: Elemento SignatureValue vuoto
Salve quando provo a generare una richiesta, l'elemento `<SignatureValue />` è vuoto. Questo causa il seguente errore durante la richiesta post diretta allo spid test env:
`TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'`

immagine

Un esempio di richiesta generata è il seguente:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceIndex="0" AttributeConsumingServiceIndex="1" Destination="http://localhost:8088/sso" ID="_53d4af8588354677b4f9cf383b4805c4" IssueInstant="2021-02-26T21:54:23.687Z" Version="2.0">
   <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="http://localhost:8080">http://localhost:8080</saml2:Issuer>
   <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
         <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
         <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
         <ds:Reference URI="#_53d4af8588354677b4f9cf383b4805c4">
            <ds:Transforms>
               <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
               <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
            <ds:DigestValue />
         </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue />
      <ds:KeyInfo>
         <ds:KeyValue>
            <ds:RSAKeyValue>
               <ds:Modulus>vx4qAxptDe6NkHqXGUTRurYXLuXy5kja0x0So1JVQOOluKwtDHVrlcophtkCNr5TI1Vc6znGuwro
j6OKepo6PLsjPVWYZq+mLZKUyJ6/yFOPDDQwfsvNMxjZ28j6hFE+fPozQ2WPltQsRBOXipn/InhV
M1HM+tIwJ6+PK4eRJkaXo6aPD45ffYwlA21jZYp5hcjCGvwG8FNIZrUbLqjwppcY7vcN2LpiAm4t
ypachQzJOqKJx1F1UZE4wEE1H8yHZgtdo3wL0NGGZ5zRiV5ECjHvpz+EYckBL9DDpzFy95g7tn0S
zTcB/ktIQL4iKfnzezHl5jMBf8tJPn6ImOE69w==</ds:Modulus>
               <ds:Exponent>AQAB</ds:Exponent>
            </ds:RSAKeyValue>
         </ds:KeyValue>
         <ds:X509Data>
            <ds:X509Certificate>MIIEMDCCAxigAwIBAgIJAK8BDpV2YZ66MA0GCSqGSIb3DQEBCwUAMIGsMQswCQYDVQQGEwJJVDER
MA8GA1UECAwIVmVyY2VsbGkxETAPBgNVBAcMCFZlcmNlbGxpMRswGQYDVQQKDBJDb211bmUgZGkg
VmVyY2VsbGkxDTALBgNVBAsMBFNwaWQxHzAdBgNVBAMMFmNvbXVuZS52ZXJjZWxsaS5nb3YuaXQx
KjAoBgkqhkiG9w0BCQEWG3NwaWRAY29tdW5lLnZlcmNlbGxpLmdvdi5pdDAeFw0yMTAyMjYxNTU0
NDRaFw0yNDAyMjYxNTU0NDRaMIGsMQswCQYDVQQGEwJJVDERMA8GA1UECAwIVmVyY2VsbGkxETAP
BgNVBAcMCFZlcmNlbGxpMRswGQYDVQQKDBJDb211bmUgZGkgVmVyY2VsbGkxDTALBgNVBAsMBFNw
aWQxHzAdBgNVBAMMFmNvbXVuZS52ZXJjZWxsaS5nb3YuaXQxKjAoBgkqhkiG9w0BCQEWG3NwaWRA
Y29tdW5lLnZlcmNlbGxpLmdvdi5pdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL8e
KgMabQ3ujZB6lxlE0bq2Fy7l8uZI2tMdEqNSVUDjpbisLQx1a5XKKYbZAja+UyNVXOs5xrsK6I+j
inqaOjy7Iz1VmGavpi2SlMiev8hTjww0MH7LzTMY2dvI+oRRPnz6M0Nlj5bULEQTl4qZ/yJ4VTNR
zPrSMCevjyuHkSZGl6Omjw+OX32MJQNtY2WKeYXIwhr8BvBTSGa1Gy6o8KaXGO73Ddi6YgJuLcqW
nIUMyTqiicdRdVGROMBBNR/Mh2YLXaN8C9DRhmec0YleRAox76c/hGHJAS/Qw6cxcveYO7Z9Es03
Af5LSEC+Iin583sx5eYzAX/LST5+iJjhOvcCAwEAAaNTMFEwHQYDVR0OBBYEFDIUYHNbbiU61Tuw
v6GEJ+OM+eO1MB8GA1UdIwQYMBaAFDIUYHNbbiU61Tuwv6GEJ+OM+eO1MA8GA1UdEwEB/wQFMAMB
Af8wDQYJKoZIhvcNAQELBQADggEBAI/pCiIce1EJkSu8Nt/t8C2veVE9PlKKcVTIkk7FsEBPgOeN
y0iMvJzWeunj1/oJWl2EGVPQP1WCkv2wPipFyo4q3sudzK3yeIPRBrdllCqmtIEsQ/tb+fgNbVyP
EHQ0495eQlwOk4M6YIsmFRt4czKMF2RvgorXbWRCh1enLTkLsR8M3kA82olM0IOUH1KWTLr1df27
3GgJk6sCl5TF/xEhk9fGvvabM476t8ZnCktimvjTk9+ZvH0AIGHRrlcMpPrFSIOmCLnWV0hhMZCF
K0xRJhsKMZqmQmamL1MxLOC8Wuckqw29JQxNV2LqOXZzJ8DWQpG1+y07Y/Gnq4r7FoM=</ds:X509Certificate>
         </ds:X509Data>
      </ds:KeyInfo>
   </ds:Signature>
   <saml2p:NameIDPolicy xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" />
   <saml2p:RequestedAuthnContext xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Comparison="exact">
      <saml:AuthnContextClassRef xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://www.spid.gov.it/SpidL2</saml:AuthnContextClassRef>
   </saml2p:RequestedAuthnContext>
</samlp:AuthnRequest>
```

### PR DESCRIPTION
**Pull request by Nick87**
### AuthNRequest fixes
- isPassive attribute is not allowed  (partially addresses #11)

see https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html

> nell’elemento <AuthnRequest> non deve essere presente l’attributo IsPassive (ad indicare false come valore di default)

see https://www.spid.gov.it/assets/download/SPID_QAD.pdf

> 2.1.11 - The IsPassive attribute must not be present

- both AssertionConsumerServiceIndex and AssertionConsumerServiceUrl+ProtocolBinding must not be set (partially addresses #11)

From spid-testenv2 validation:

> "Uno e uno solo uno tra gli attributi o gruppi di attributi devono essere presenti: [AssertionConsumerServiceIndex, [AssertionConsumerServiceUrl, ProtocolBinding]]"

see https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html

> In alternativa all’attributo AssertionConsumerServiceIndex (scelta sconsigliata) possono essere presenti:
l’attributo AssertionConsumerServiceURL [...]
l’attributo ProtocolBinding [...]

- ForceAuthn attribute must be present if SPID level > 1 (partially addresses #11)

see https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html

> l’attributo ForceAuthn nel caso in cui si richieda livelli di autenticazione superiori a SpidL1 (SpidL2 o SpidL3)

- Issuer must be set to "urn:oasis:names:tc:SAML:2.0:nameid-format:entity" not to "urn:oasis:names:tc:SAML:2.0:nameid-format:transient" (partially addresses #11)

see https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html

> L’elemento deve riportare gli attributi: Format fissato al valore urn:oasis:names:tc:SAML:2.0:nameid-format:entity

see https://www.spid.gov.it/assets/download/SPID_QAD.pdf

> 2.2.4 - The Format attribute must be urn:oasis:names:tc:SAML:2.0:nameidformat:entity

- The same public key info is provided twice in getSignature() (explicitly and via certificate), resulting in having both KeyValue and X509Data elements present in the AuthnRequest, making signxml throwing an exception when using spid-testenv2. Fixes #10.

see https://github.com/XML-Security/signxml/issues/143

As a fix, public key info is now only added via certificate (commenting KeyInfoHelper.addPublicKey(keyInfo, certificate.getPublicKey()); in getSignature()) and adding Signer.signObject(authnRequest.getSignature()); to printAuthnRequest

see https://github.com/italia/spid-testenv2/issues/325

- comparison set to MINIMUM in AuthNContext (partially addresses #11)

### Other minor changes:
- added maven generated dirs to .gitignore
- privateKey must not be logged
- option to not compress authnrequest when using POST binding (partially addresses #11)
- added lombok

### CODE REVIEW

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/AuthenticationInfoExtractor.java [hunk 1]
```diff
@@ -188,10 +189,11 @@ public AuthnRequest buildAuthenticationRequest(String assertionConsumerServiceUr
 		AuthnRequestBuilder authRequestBuilder = new AuthnRequestBuilder();
 
 		AuthnRequest authRequest = authRequestBuilder.buildObject(SAML2_PROTOCOL, "AuthnRequest", "samlp");
-		authRequest.setIsPassive(Boolean.FALSE);
+		authRequest.setForceAuthn(Boolean.TRUE);
+		// authRequest.setIsPassive(Boolean.FALSE);
```
Comment (polarene) [inline spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/AuthenticationInfoExtractor.java]: There shouldn't be commented-out lines left in production code.
```suggestion
```

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/AuthenticationInfoExtractor.java [hunk 2]
```diff
@@ -188,10 +189,11 @@ public AuthnRequest buildAuthenticationRequest(String assertionConsumerServiceUr
...
 		authRequest.setIssueInstant(issueInstant);
-		authRequest.setProtocolBinding(SAML2_POST_BINDING);
-		authRequest.setAssertionConsumerServiceURL(assertionConsumerServiceUrl);
+		// authRequest.setProtocolBinding(SAML2_POST_BINDING);
+		// authRequest.setAssertionConsumerServiceURL(assertionConsumerServiceUrl);
```
Comment (polarene) [inline spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/AuthenticationInfoExtractor.java]: There shouldn't be commented-out lines left in production code.
```suggestion
```

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java [hunk 3]
```diff
@@ -130,6 +135,13 @@ public String printAuthnRequest(AuthnRequest authnRequest) throws IntegrationSer
 			log.error("printAuthnRequest :: " + e.getMessage(), e);
 			throw new IntegrationServiceException(e);
 		}
+		
+		try {
+			Signer.signObject(authnRequest.getSignature());
+		} catch (SignatureException e) {
+			  e.printStackTrace();
```
Comment (polarene) [inline spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java]: Consider using an error log instead of printStackTrace(), for example:
```suggestion
			  log.error("There was an error while signing the request", e);
```

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java [hunk 4]
```diff
@@ -172,7 +184,7 @@ public Credential getCredential() {
 		credential.setEntityCertificate(certificate);
 		credential.setPrivateKey(pk);
 
-		log.info("Private Key" + pk.toString());
+		// log.info("Private Key" + pk.toString());
```
Comment (polarene) [inline spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java]: There shouldn't be commented-out lines left in production code. Besides, a private key being sensible data, maybe it could be logged at least at DEBUG level?

```suggestion
		log.debug("Private Key: {}", pk);
```

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java [hunk 5]
```diff
@@ -223,7 +235,7 @@ public Signature getSignature() {
 		KeyStore ks = getKeyStore();
 		try {
 			X509Certificate certificate = (X509Certificate) ks.getCertificate(certificateAliasName);
-			KeyInfoHelper.addPublicKey(keyInfo, certificate.getPublicKey());
+			// KeyInfoHelper.addPublicKey(keyInfo, certificate.getPublicKey());
```
Comment (polarene) [inline spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java]: There shouldn't be commented-out lines left in production code.

```suggestion
```

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java (hunk 4 above)
Comment (Nick87) [reply spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java]: I disagree. I think this is still dangerous and to be avoided: private keys should never be logged. I removed the commented code altogether.

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java (hunk 3 above)
Comment (Nick87) [reply spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java]: Added logging statement as well as throwing an exception

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java (hunk 4 above)
Comment (polarene) [reply spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java]: Cool, probably it's the best.

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java [hunk 6]
```diff
@@ -139,7 +139,8 @@ public String printAuthnRequest(AuthnRequest authnRequest) throws IntegrationSer
 		try {
 			Signer.signObject(authnRequest.getSignature());
 		} catch (SignatureException e) {
-			  e.printStackTrace();
+			log.error("There was an error while signing the request", e);
+			throw new IntegrationServiceException(e);
```
Comment (polarene) [inline spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java]: Consider avoiding this log-and-throw pattern to avoid log duplication, maybe have a read here https://stackify.com/best-practices-exceptions-java/ (point 8).

**Review by polarene — APPROVED** [review]
Left just an observation, nice PR!

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/AuthenticationInfoExtractor.java (hunk 1 above)
Comment (Nick87) [reply spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/AuthenticationInfoExtractor.java]: commented code removed

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java (hunk 5 above)
Comment (Nick87) [reply spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java]: commented code removed

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/AuthenticationInfoExtractor.java (hunk 2 above)
Comment (Nick87) [reply spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/AuthenticationInfoExtractor.java]: commented code removed

File: spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java (hunk 6 above)
Comment (Nick87) [reply spid-spring-integration/src/main/java/it/italia/developers/spid/integration/util/SPIDIntegrationUtil.java]: removed log statement, kept exception throwing

**Comment by peppelinux** [comment]
thank you @Nick87 @polarene
